[build-system]
requires = ["maturin>=1.14,<2"]
build-backend = "maturin"

[project]
name = "otadump"
dynamic = ["version"]
description = "Extract partitions from Android OTA files"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = [
    "LICENSE",
    "src/puffin/LICENSE",
    "native/lz4/LICENSE",
    "native/zucchini/vendor/zucchini/LICENSE",
    "native/zucchini/vendor/libchrome/NOTICE",
    "native/zucchini/vendor/libchrome/base/third_party/icu/LICENSE",
    "native/zucchini/vendor/libchrome/base/third_party/nspr/LICENSE",
    "native/zucchini/vendor/libchrome/base/third_party/nspr/MPL-1.1.txt",
]
authors = [
    { name = "Kartik Sharma", email = "kartik.sharma522@gmail.com" },
    { name = "Ajeet D'Souza", email = "98ajeet@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
]

[tool.maturin]
features = ["python"]
locked = true
