use std::fs;
use std::path::Path;
use std::sync::atomic::{AtomicBool, Ordering};

use otadump::{CancellationToken, ExtractOptions, ProgressReporter, is_cancellation};
use prost::Message;
use ring::digest;
use tempfile::TempDir;

#[derive(Clone, PartialEq, Message)]
struct Extent {
    #[prost(uint64, optional, tag = "1")]
    start_block: Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    num_blocks: Option<u64>,
}

#[derive(Clone, PartialEq, Message)]
struct PartitionInfo {
    #[prost(uint64, optional, tag = "1")]
    size: Option<u64>,
    #[prost(bytes = "vec", optional, tag = "2")]
    hash: Option<Vec<u8>>,
}

#[derive(Clone, PartialEq, Message)]
struct InstallOperation {
    #[prost(int32, tag = "1")]
    operation_type: i32,
    #[prost(uint64, optional, tag = "2")]
    data_offset: Option<u64>,
    #[prost(uint64, optional, tag = "3")]
    data_length: Option<u64>,
    #[prost(message, repeated, tag = "4")]
    src_extents: Vec<Extent>,
    #[prost(uint64, optional, tag = "5")]
    src_length: Option<u64>,
    #[prost(message, repeated, tag = "6")]
    dst_extents: Vec<Extent>,
    #[prost(uint64, optional, tag = "7")]
    dst_length: Option<u64>,
    #[prost(bytes = "vec", optional, tag = "8")]
    data_sha256_hash: Option<Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "9")]
    src_sha256_hash: Option<Vec<u8>>,
}

#[derive(Clone, PartialEq, Message)]
struct PartitionUpdate {
    #[prost(string, tag = "1")]
    partition_name: String,
    #[prost(message, optional, tag = "6")]
    old_partition_info: Option<PartitionInfo>,
    #[prost(message, optional, tag = "7")]
    new_partition_info: Option<PartitionInfo>,
    #[prost(message, repeated, tag = "8")]
    operations: Vec<InstallOperation>,
}

#[derive(Clone, PartialEq, Message)]
struct DeltaArchiveManifest {
    #[prost(uint32, optional, tag = "3")]
    block_size: Option<u32>,
    #[prost(uint32, optional, tag = "12")]
    minor_version: Option<u32>,
    #[prost(message, repeated, tag = "13")]
    partitions: Vec<PartitionUpdate>,
}

fn sha256(bytes: &[u8]) -> Vec<u8> {
    digest::digest(&digest::SHA256, bytes).as_ref().to_vec()
}

// Hand-authored BSDIFF40 and BSDF2 fixtures. The test data is covered by this
// project's MIT license and was not generated by the patch implementation.
const BSDIFF40_PATCH: &[u8] = &[
    66, 83, 68, 73, 70, 70, 52, 48, 41, 0, 0, 0, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0,
    0, 0, 0, 0, 66, 90, 104, 57, 49, 65, 89, 38, 83, 89, 184, 173, 85, 59, 0, 0, 2, 96, 0, 64, 64,
    8, 0, 32, 0, 48, 204, 12, 245, 5, 206, 46, 228, 138, 112, 161, 33, 113, 90, 170, 118, 66, 90,
    104, 57, 49, 65, 89, 38, 83, 89, 168, 46, 248, 254, 0, 0, 2, 192, 0, 192, 0, 2, 0, 32, 0, 48,
    128, 103, 161, 185, 11, 185, 34, 156, 40, 72, 84, 23, 124, 127, 0, 66, 90, 104, 57, 23, 114,
    69, 56, 80, 144, 0, 0, 0, 0,
];
const BROTLI_BSDF2_PATCH: &[u8] = &[
    66, 83, 68, 70, 50, 2, 2, 2, 12, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
    0, 0, 0, 31, 23, 0, 248, 167, 0, 16, 98, 141, 0, 160, 0, 143, 3, 128, 0, 0, 245, 245, 0, 0, 0,
    0, 3, 63,
];
const BROTLI_INVALID_HEADER_PATCH: &[u8] = &[
    66, 83, 68, 70, 50, 2, 2, 2, 12, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
    0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
];

fn extent(start_block: u64, num_blocks: u64) -> Extent {
    Extent { start_block: Some(start_block), num_blocks: Some(num_blocks) }
}

fn write_payload(path: &Path, manifest: DeltaArchiveManifest, data: &[u8]) {
    let manifest = manifest.encode_to_vec();
    let mut payload = Vec::with_capacity(24 + manifest.len() + data.len());
    payload.extend_from_slice(b"CrAU");
    payload.extend_from_slice(&2u64.to_be_bytes());
    payload.extend_from_slice(&(manifest.len() as u64).to_be_bytes());
    payload.extend_from_slice(&0u32.to_be_bytes());
    payload.extend_from_slice(&manifest);
    payload.extend_from_slice(data);
    fs::write(path, payload).unwrap();
}

fn partition_info(bytes: &[u8]) -> PartitionInfo {
    PartitionInfo { size: Some(bytes.len() as u64), hash: Some(sha256(bytes)) }
}

#[test]
fn source_copy_reconstructs_noncontiguous_extents_without_modifying_source() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let source = b"AAAABBBBCCCCDDDD";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let expected = b"AAAACCCC";
    let operation = InstallOperation {
        operation_type: 4,
        src_extents: vec![extent(2, 1), extent(0, 1)],
        src_length: Some(8),
        dst_extents: vec![extent(1, 1), extent(0, 1)],
        dst_length: Some(8),
        src_sha256_hash: Some(sha256(b"CCCCAAAA")),
        ..Default::default()
    };
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(source)),
            new_partition_info: Some(partition_info(expected)),
            operations: vec![operation],
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    ExtractOptions::new()
        .source_dir(&source_dir)
        .num_threads(2)
        .extract(&payload, &output_dir)
        .unwrap();

    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), expected);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
}

#[test]
fn source_bsdiff_reconstructs_bsdiff40_without_modifying_source() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let source = b"abcdefgh";
    let expected = b"abXYefgh";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(1),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(source)),
            new_partition_info: Some(partition_info(expected)),
            operations: vec![InstallOperation {
                operation_type: 5,
                data_offset: Some(0),
                data_length: Some(BSDIFF40_PATCH.len() as u64),
                src_extents: vec![extent(0, source.len() as u64)],
                src_length: Some(source.len() as u64),
                dst_extents: vec![extent(0, expected.len() as u64)],
                dst_length: Some(expected.len() as u64),
                data_sha256_hash: Some(sha256(BSDIFF40_PATCH)),
                src_sha256_hash: Some(sha256(source)),
            }],
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, BSDIFF40_PATCH);

    ExtractOptions::new()
        .source_dir(&source_dir)
        .num_threads(2)
        .extract(&payload, &output_dir)
        .unwrap();

    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), expected);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
}

#[test]
fn brotli_bsdiff_reconstructs_bsdf2_without_modifying_source() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let source = b"abcdefgh";
    let expected = b"abXYefgh";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(1),
        minor_version: Some(4),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(source)),
            new_partition_info: Some(partition_info(expected)),
            operations: vec![InstallOperation {
                operation_type: 10,
                data_offset: Some(0),
                data_length: Some(BROTLI_BSDF2_PATCH.len() as u64),
                src_extents: vec![extent(0, source.len() as u64)],
                src_length: Some(source.len() as u64),
                dst_extents: vec![extent(0, expected.len() as u64)],
                dst_length: Some(expected.len() as u64),
                data_sha256_hash: Some(sha256(BROTLI_BSDF2_PATCH)),
                src_sha256_hash: Some(sha256(source)),
            }],
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, BROTLI_BSDF2_PATCH);

    ExtractOptions::new()
        .source_dir(&source_dir)
        .num_threads(2)
        .extract(&payload, &output_dir)
        .unwrap();

    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), expected);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
}

#[test]
fn malformed_bsdiff_headers_fail_cleanly_and_remove_staging() {
    for (operation_type, patch, expected_error) in [
        (5, &[0; 32][..], "SOURCE_BSDIFF patch is invalid"),
        (10, BROTLI_INVALID_HEADER_PATCH, "BROTLI_BSDIFF patch is invalid"),
    ] {
        let temporary = TempDir::new().unwrap();
        let source_dir = temporary.path().join("source");
        let output_dir = temporary.path().join("output");
        fs::create_dir(&source_dir).unwrap();
        let source = b"abcdefgh";
        fs::write(source_dir.join("system.img"), source).unwrap();
        let manifest = DeltaArchiveManifest {
            block_size: Some(1),
            minor_version: Some(4),
            partitions: vec![PartitionUpdate {
                partition_name: "system".into(),
                old_partition_info: Some(partition_info(source)),
                new_partition_info: Some(partition_info(b"abXYefgh")),
                operations: vec![InstallOperation {
                    operation_type,
                    data_offset: Some(0),
                    data_length: Some(patch.len() as u64),
                    src_extents: vec![extent(0, source.len() as u64)],
                    src_length: Some(source.len() as u64),
                    dst_extents: vec![extent(0, source.len() as u64)],
                    dst_length: Some(source.len() as u64),
                    data_sha256_hash: Some(sha256(patch)),
                    src_sha256_hash: Some(sha256(source)),
                }],
            }],
        };
        let payload = temporary.path().join("payload.bin");
        write_payload(&payload, manifest, patch);

        let error = ExtractOptions::new()
            .source_dir(&source_dir)
            .num_threads(2)
            .extract(&payload, &output_dir)
            .unwrap_err()
            .to_string();

        assert!(error.contains(expected_error), "unexpected error: {error}");
        assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
        assert!(!output_dir.join("system.img").exists());
        assert!(fs::read_dir(&output_dir).unwrap().next().is_none());
    }
}

#[test]
fn source_validation_rejects_wrong_base_before_creating_output() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    fs::write(source_dir.join("boot.img"), b"bad!").unwrap();
    let operation = InstallOperation {
        operation_type: 4,
        src_extents: vec![extent(0, 1)],
        dst_extents: vec![extent(0, 1)],
        ..Default::default()
    };
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "boot".into(),
            old_partition_info: Some(partition_info(b"good")),
            new_partition_info: Some(partition_info(b"good")),
            operations: vec![operation],
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let error = ExtractOptions::new()
        .source_dir(&source_dir)
        .extract(&payload, &output_dir)
        .unwrap_err()
        .to_string();

    assert!(error.contains("Source partition hash mismatch"));
    assert!(!output_dir.join("boot.img").exists());
}

#[test]
fn padded_source_uses_declared_prefix_without_modifying_tail() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let declared_source = b"base";
    let source = b"basefooter";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(declared_source)),
            new_partition_info: Some(partition_info(declared_source)),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(0, 1)],
                src_length: Some(4),
                dst_extents: vec![extent(0, 1)],
                dst_length: Some(4),
                src_sha256_hash: Some(sha256(declared_source)),
                ..Default::default()
            }],
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    ExtractOptions::new().source_dir(&source_dir).extract(&payload, &output_dir).unwrap();

    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), declared_source);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
}

#[test]
fn source_shorter_than_declared_size_fails_cleanly() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let source = b"bas";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let declared_source = b"base";
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(declared_source)),
            new_partition_info: Some(partition_info(declared_source)),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(0, 1)],
                dst_extents: vec![extent(0, 1)],
                ..Default::default()
            }],
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let error = ExtractOptions::new()
        .source_dir(&source_dir)
        .extract(&payload, &output_dir)
        .unwrap_err()
        .to_string();

    assert!(error.contains("Source partition size mismatch"), "unexpected error: {error}");
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
    assert!(!output_dir.join("system.img").exists());
}

#[test]
fn source_extent_cannot_enter_padding_beyond_declared_size() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let declared_source = b"base";
    let source = b"basefoot";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(declared_source)),
            new_partition_info: Some(partition_info(declared_source)),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(1, 1)],
                src_length: Some(4),
                dst_extents: vec![extent(0, 1)],
                dst_length: Some(4),
                src_sha256_hash: Some(sha256(b"foot")),
                ..Default::default()
            }],
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let error = ExtractOptions::new()
        .source_dir(&source_dir)
        .extract(&payload, &output_dir)
        .unwrap_err()
        .to_string();

    assert!(error.contains("Invalid source extents"), "unexpected error: {error}");
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
    assert!(!output_dir.join("system.img").exists());
}

#[test]
fn delta_operation_without_source_directory_fails_clearly() {
    let temporary = TempDir::new().unwrap();
    let output_dir = temporary.path().join("output");
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "boot".into(),
            old_partition_info: Some(partition_info(b"base")),
            new_partition_info: Some(partition_info(b"base")),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(0, 1)],
                dst_extents: vec![extent(0, 1)],
                ..Default::default()
            }],
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let error = ExtractOptions::new().extract(&payload, &output_dir).unwrap_err().to_string();

    assert!(error.contains("require a source directory"));
    assert!(!output_dir.join("boot.img").exists());
}

#[test]
fn malformed_partition_layouts_fail_without_escaping_or_leaving_partial_images() {
    for (name, operations, expected_error) in [
        (
            "../escape",
            vec![InstallOperation {
                operation_type: 0,
                data_offset: Some(0),
                data_length: Some(4),
                dst_extents: vec![extent(0, 1)],
                ..Default::default()
            }],
            "Unsafe partition name",
        ),
        (
            "system",
            vec![
                InstallOperation {
                    operation_type: 0,
                    data_offset: Some(0),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                },
                InstallOperation {
                    operation_type: 0,
                    data_offset: Some(4),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                },
            ],
            "Destination extents overlap",
        ),
    ] {
        let temporary = TempDir::new().unwrap();
        let output_dir = temporary.path().join("output");
        let target = b"data";
        let manifest = DeltaArchiveManifest {
            block_size: Some(4),
            minor_version: Some(0),
            partitions: vec![PartitionUpdate {
                partition_name: name.into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(target)),
                operations,
            }],
        };
        let payload = temporary.path().join("payload.bin");
        write_payload(&payload, manifest, b"datadata");

        let error = ExtractOptions::new().extract(&payload, &output_dir).unwrap_err().to_string();

        assert!(error.contains(expected_error), "unexpected error: {error}");
        assert!(!temporary.path().join("escape.img").exists());
        assert!(!output_dir.join("system.img").exists());
    }
}

#[test]
fn full_replace_payload_remains_compatible() {
    let temporary = TempDir::new().unwrap();
    let output_dir = temporary.path().join("output");
    let expected = b"full payload data";
    let operation = InstallOperation {
        operation_type: 0,
        data_offset: Some(0),
        data_length: Some(expected.len() as u64),
        dst_extents: vec![extent(0, 2)],
        data_sha256_hash: Some(sha256(expected)),
        ..Default::default()
    };
    let mut padded = expected.to_vec();
    padded.resize(32, 0);
    let manifest = DeltaArchiveManifest {
        block_size: Some(16),
        minor_version: Some(0),
        partitions: vec![PartitionUpdate {
            partition_name: "vendor".into(),
            old_partition_info: None,
            new_partition_info: Some(partition_info(&padded)),
            operations: vec![operation],
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, expected);

    ExtractOptions::new().extract(&payload, &output_dir).unwrap();

    assert_eq!(fs::read(output_dir.join("vendor.img")).unwrap(), padded);
}

#[test]
fn verified_partitions_are_promoted_after_all_succeed() {
    let temporary = TempDir::new().unwrap();
    let output_dir = temporary.path().join("output");
    let boot = b"boot";
    let vendor = b"vend";
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(0),
        partitions: vec![
            PartitionUpdate {
                partition_name: "boot".into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(boot)),
                operations: vec![InstallOperation {
                    operation_type: 0,
                    data_offset: Some(0),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
            },
            PartitionUpdate {
                partition_name: "vendor".into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(vendor)),
                operations: vec![InstallOperation {
                    operation_type: 0,
                    data_offset: Some(4),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
            },
        ],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, b"bootvend");

    ExtractOptions::new().extract(&payload, &output_dir).unwrap();

    assert_eq!(fs::read(output_dir.join("boot.img")).unwrap(), boot);
    assert_eq!(fs::read(output_dir.join("vendor.img")).unwrap(), vendor);
}

#[test]
fn no_clobber_rejects_existing_destination_without_modifying_source() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    fs::create_dir(&output_dir).unwrap();
    let source = b"base";
    let existing = b"keep";
    fs::write(source_dir.join("system.img"), source).unwrap();
    fs::write(output_dir.join("system.img"), existing).unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(source)),
            new_partition_info: Some(partition_info(source)),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(0, 1)],
                dst_extents: vec![extent(0, 1)],
                ..Default::default()
            }],
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let error = ExtractOptions::new()
        .source_dir(&source_dir)
        .extract(&payload, &output_dir)
        .unwrap_err()
        .to_string();

    assert!(error.contains("already exists"));
    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), existing);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
    assert_eq!(fs::read_dir(&output_dir).unwrap().count(), 1);
}

#[test]
fn verification_failure_preserves_existing_destinations_with_overwrite() {
    let temporary = TempDir::new().unwrap();
    let output_dir = temporary.path().join("output");
    fs::create_dir(&output_dir).unwrap();
    fs::write(output_dir.join("boot.img"), b"oldb").unwrap();
    fs::write(output_dir.join("vendor.img"), b"oldv").unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(0),
        partitions: vec![
            PartitionUpdate {
                partition_name: "boot".into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(b"boot")),
                operations: vec![InstallOperation {
                    operation_type: 0,
                    data_offset: Some(0),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
            },
            PartitionUpdate {
                partition_name: "vendor".into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(b"bad!")),
                operations: vec![InstallOperation {
                    operation_type: 0,
                    data_offset: Some(4),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
            },
        ],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, b"bootvend");

    let error = ExtractOptions::new()
        .overwrite(true)
        .extract(&payload, &output_dir)
        .unwrap_err()
        .to_string();

    assert!(error.contains("Output verification failed"));
    assert_eq!(fs::read(output_dir.join("boot.img")).unwrap(), b"oldb");
    assert_eq!(fs::read(output_dir.join("vendor.img")).unwrap(), b"oldv");
    assert_eq!(fs::read_dir(&output_dir).unwrap().count(), 2);
}

#[test]
fn partition_selection_does_not_require_unselected_delta_sources() {
    let temporary = TempDir::new().unwrap();
    let output_dir = temporary.path().join("output");
    let expected = b"boot";
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![
            PartitionUpdate {
                partition_name: "boot".into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(expected)),
                operations: vec![InstallOperation {
                    operation_type: 0,
                    data_offset: Some(0),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
            },
            PartitionUpdate {
                partition_name: "system".into(),
                old_partition_info: Some(partition_info(b"base")),
                new_partition_info: Some(partition_info(b"base")),
                operations: vec![InstallOperation {
                    operation_type: 4,
                    src_extents: vec![extent(0, 1)],
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
            },
        ],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, expected);

    ExtractOptions::new().partitions(["boot"]).extract(&payload, &output_dir).unwrap();

    assert_eq!(fs::read(output_dir.join("boot.img")).unwrap(), expected);
    assert!(!output_dir.join("system.img").exists());
}

struct CancellingReporter {
    cancellation_token: CancellationToken,
    cancelled: AtomicBool,
}

impl ProgressReporter for CancellingReporter {
    fn report_progress(&self, progress: f64) {
        if progress > 0.0 && !self.cancelled.swap(true, Ordering::AcqRel) {
            self.cancellation_token.cancel();
        }
    }
}

#[test]
fn cancellation_cleans_staging_without_promoting_or_modifying_source() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    fs::create_dir(&output_dir).unwrap();
    let source = (0..128).map(|byte| byte as u8).collect::<Vec<_>>();
    fs::write(source_dir.join("system.img"), &source).unwrap();
    let existing = b"existing destination";
    fs::write(output_dir.join("system.img"), existing).unwrap();
    let operations = (0..32)
        .map(|block| InstallOperation {
            operation_type: 4,
            src_extents: vec![extent(block, 1)],
            src_length: Some(4),
            dst_extents: vec![extent(block, 1)],
            dst_length: Some(4),
            ..Default::default()
        })
        .collect();
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(&source)),
            new_partition_info: Some(partition_info(&source)),
            operations,
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);
    let cancellation_token = CancellationToken::new();
    let reporter = CancellingReporter {
        cancellation_token: cancellation_token.clone(),
        cancelled: AtomicBool::new(false),
    };

    let error = ExtractOptions::new()
        .source_dir(&source_dir)
        .overwrite(true)
        .num_threads(4)
        .progress_reporter(&reporter)
        .cancellation_token(&cancellation_token)
        .extract(&payload, &output_dir)
        .unwrap_err();

    assert!(is_cancellation(error.as_ref()));
    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), existing);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
    assert!(
        fs::read_dir(&output_dir).unwrap().all(|entry| !entry
            .unwrap()
            .file_name()
            .to_string_lossy()
            .starts_with(".otadump-"))
    );
}

#[test]
fn cli_extraction_error_exits_nonzero_and_reports_diagnostic() {
    use std::process::Command;

    let temporary = TempDir::new().unwrap();
    let payload = temporary.path().join("payload.bin");
    let output_dir = temporary.path().join("output");
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "boot".into(),
            old_partition_info: Some(partition_info(b"base")),
            new_partition_info: Some(partition_info(b"base")),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(0, 1)],
                dst_extents: vec![extent(0, 1)],
                ..Default::default()
            }],
        }],
    };
    write_payload(&payload, manifest, &[]);

    let output = Command::new(env!("CARGO_BIN_EXE_otadump"))
        .arg(&payload)
        .arg("--output-dir")
        .arg(&output_dir)
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert_eq!(output.status.code(), Some(1), "CLI did not exit with code 1; stderr: {stderr}");
    assert!(
        stderr.contains("require a source directory"),
        "missing extraction diagnostic: {stderr}"
    );
}

#[cfg(unix)]
#[test]
fn cli_sigint_exits_130_after_cleaning_staging() {
    use std::process::{Command, Stdio};
    use std::time::{Duration, Instant};

    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let block_size = 256usize;
    let block_count = 65_536usize;
    let source = vec![0x5a; block_size * block_count];
    let source_path = source_dir.join("system.img");
    fs::write(&source_path, &source).unwrap();
    let operations = (0..block_count)
        .map(|block| InstallOperation {
            operation_type: 4,
            src_extents: vec![extent(block as u64, 1)],
            src_length: Some(block_size as u64),
            dst_extents: vec![extent(block as u64, 1)],
            dst_length: Some(block_size as u64),
            ..Default::default()
        })
        .collect();
    let manifest = DeltaArchiveManifest {
        block_size: Some(block_size as u32),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(&source)),
            new_partition_info: Some(partition_info(&source)),
            operations,
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let mut child = Command::new(env!("CARGO_BIN_EXE_otadump"))
        .arg(&payload)
        .arg("--output-dir")
        .arg(&output_dir)
        .arg("--source-dir")
        .arg(&source_dir)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .unwrap();
    let deadline = Instant::now() + Duration::from_secs(10);
    loop {
        let staging_exists = output_dir.exists()
            && fs::read_dir(&output_dir)
                .unwrap()
                .any(|entry| entry.unwrap().file_name().to_string_lossy().starts_with(".otadump-"));
        if staging_exists {
            break;
        }
        assert!(child.try_wait().unwrap().is_none(), "CLI finished before SIGINT");
        assert!(Instant::now() < deadline, "staging directory was not created");
        std::thread::yield_now();
    }
    let signal_status =
        Command::new("kill").arg("-INT").arg(child.id().to_string()).status().unwrap();
    assert!(signal_status.success());
    let exit_deadline = Instant::now() + Duration::from_secs(10);
    let status = loop {
        if let Some(status) = child.try_wait().unwrap() {
            break status;
        }
        if Instant::now() >= exit_deadline {
            child.kill().unwrap();
            child.wait().unwrap();
            panic!("CLI did not finish cleanup after SIGINT");
        }
        std::thread::sleep(Duration::from_millis(1));
    };

    assert_eq!(status.code(), Some(130));
    assert!(!output_dir.join("system.img").exists());
    assert_eq!(sha256(&fs::read(source_path).unwrap()), sha256(&source));
    assert!(fs::read_dir(&output_dir).unwrap().next().is_none());
}

#[cfg(unix)]
#[test]
fn source_and_destination_aliases_are_rejected_without_modifying_the_source() {
    use std::os::unix::fs::symlink;

    for link in ["hard", "symbolic"] {
        let temporary = TempDir::new().unwrap();
        let source_dir = temporary.path().join("source");
        let output_dir = temporary.path().join("output");
        fs::create_dir(&source_dir).unwrap();
        fs::create_dir(&output_dir).unwrap();
        let source_path = source_dir.join("system.img");
        let source = b"base";
        fs::write(&source_path, source).unwrap();
        let destination_path = output_dir.join("system.img");
        if link == "hard" {
            fs::hard_link(&source_path, &destination_path).unwrap();
        } else {
            symlink(&source_path, &destination_path).unwrap();
        }

        let manifest = DeltaArchiveManifest {
            block_size: Some(4),
            minor_version: Some(2),
            partitions: vec![PartitionUpdate {
                partition_name: "system".into(),
                old_partition_info: Some(partition_info(source)),
                new_partition_info: Some(partition_info(source)),
                operations: vec![InstallOperation {
                    operation_type: 4,
                    src_extents: vec![extent(0, 1)],
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
            }],
        };
        let payload = temporary.path().join("payload.bin");
        write_payload(&payload, manifest, &[]);

        let error = ExtractOptions::new()
            .source_dir(&source_dir)
            .overwrite(true)
            .extract(&payload, &output_dir)
            .unwrap_err()
            .to_string();

        assert!(error.contains("refer to the same file"));
        assert_eq!(fs::read(&source_path).unwrap(), source);
    }
}
