use std::fs;
#[cfg(otadump_zucchini)]
use std::io::Write;
use std::path::Path;
use std::sync::atomic::{AtomicBool, Ordering};

use otadump::{CancellationToken, ExtractOptions, ProgressReporter, is_cancellation};
use prost::Message;
use ring::digest;
use tempfile::TempDir;

#[derive(Clone, PartialEq, Message)]
struct Extent {
    #[prost(uint64, optional, tag = "1")]
    start_block: Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    num_blocks: Option<u64>,
}

#[derive(Clone, PartialEq, Message)]
struct PartitionInfo {
    #[prost(uint64, optional, tag = "1")]
    size: Option<u64>,
    #[prost(bytes = "vec", optional, tag = "2")]
    hash: Option<Vec<u8>>,
}

#[derive(Clone, PartialEq, Message)]
struct InstallOperation {
    #[prost(int32, tag = "1")]
    operation_type: i32,
    #[prost(uint64, optional, tag = "2")]
    data_offset: Option<u64>,
    #[prost(uint64, optional, tag = "3")]
    data_length: Option<u64>,
    #[prost(message, repeated, tag = "4")]
    src_extents: Vec<Extent>,
    #[prost(uint64, optional, tag = "5")]
    src_length: Option<u64>,
    #[prost(message, repeated, tag = "6")]
    dst_extents: Vec<Extent>,
    #[prost(uint64, optional, tag = "7")]
    dst_length: Option<u64>,
    #[prost(bytes = "vec", optional, tag = "8")]
    data_sha256_hash: Option<Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "9")]
    src_sha256_hash: Option<Vec<u8>>,
}

#[derive(Clone, PartialEq, Message)]
struct PartitionUpdate {
    #[prost(string, tag = "1")]
    partition_name: String,
    #[prost(message, optional, tag = "6")]
    old_partition_info: Option<PartitionInfo>,
    #[prost(message, optional, tag = "7")]
    new_partition_info: Option<PartitionInfo>,
    #[prost(message, repeated, tag = "8")]
    operations: Vec<InstallOperation>,
    #[prost(message, optional, tag = "10")]
    hash_tree_data_extent: Option<Extent>,
    #[prost(message, optional, tag = "11")]
    hash_tree_extent: Option<Extent>,
    #[prost(string, optional, tag = "12")]
    hash_tree_algorithm: Option<String>,
    #[prost(bytes = "vec", optional, tag = "13")]
    hash_tree_salt: Option<Vec<u8>>,
    #[prost(message, optional, tag = "14")]
    fec_data_extent: Option<Extent>,
    #[prost(message, optional, tag = "15")]
    fec_extent: Option<Extent>,
    #[prost(uint32, optional, tag = "16")]
    fec_roots: Option<u32>,
}

#[derive(Clone, PartialEq, Message)]
struct DeltaArchiveManifest {
    #[prost(uint32, optional, tag = "3")]
    block_size: Option<u32>,
    #[prost(uint32, optional, tag = "12")]
    minor_version: Option<u32>,
    #[prost(message, repeated, tag = "13")]
    partitions: Vec<PartitionUpdate>,
}

#[derive(Clone, Copy, PartialEq, Message)]
struct Lz4diffAlgorithm {
    #[prost(int32, tag = "1")]
    algorithm_type: i32,
    #[prost(int32, tag = "2")]
    level: i32,
}

#[derive(Clone, PartialEq, Message)]
struct Lz4diffBlock {
    #[prost(uint64, tag = "1")]
    uncompressed_offset: u64,
    #[prost(uint64, tag = "2")]
    uncompressed_length: u64,
    #[prost(uint64, tag = "3")]
    compressed_length: u64,
    #[prost(bytes = "vec", tag = "4")]
    sha256_hash: Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    postfix_bspatch: Vec<u8>,
}

#[derive(Clone, PartialEq, Message)]
struct Lz4diffCompressionInfo {
    #[prost(message, optional, tag = "1")]
    algo: Option<Lz4diffAlgorithm>,
    #[prost(message, repeated, tag = "2")]
    block_info: Vec<Lz4diffBlock>,
    #[prost(bool, tag = "3")]
    zero_padding_enabled: bool,
}

#[derive(Clone, PartialEq, Message)]
struct Lz4diffHeader {
    #[prost(message, optional, tag = "1")]
    src_info: Option<Lz4diffCompressionInfo>,
    #[prost(message, optional, tag = "2")]
    dst_info: Option<Lz4diffCompressionInfo>,
    #[prost(int32, tag = "3")]
    inner_type: i32,
}

fn sha256(bytes: &[u8]) -> Vec<u8> {
    digest::digest(&digest::SHA256, bytes).as_ref().to_vec()
}

// Hand-authored BSDIFF40 and BSDF2 fixtures. The test data is covered by this
// project's MIT license and was not generated by the patch implementation.
const BSDIFF40_PATCH: &[u8] = &[
    66, 83, 68, 73, 70, 70, 52, 48, 41, 0, 0, 0, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0,
    0, 0, 0, 0, 66, 90, 104, 57, 49, 65, 89, 38, 83, 89, 184, 173, 85, 59, 0, 0, 2, 96, 0, 64, 64,
    8, 0, 32, 0, 48, 204, 12, 245, 5, 206, 46, 228, 138, 112, 161, 33, 113, 90, 170, 118, 66, 90,
    104, 57, 49, 65, 89, 38, 83, 89, 168, 46, 248, 254, 0, 0, 2, 192, 0, 192, 0, 2, 0, 32, 0, 48,
    128, 103, 161, 185, 11, 185, 34, 156, 40, 72, 84, 23, 124, 127, 0, 66, 90, 104, 57, 23, 114,
    69, 56, 80, 144, 0, 0, 0, 0,
];
const BROTLI_BSDF2_PATCH: &[u8] = &[
    66, 83, 68, 70, 50, 2, 2, 2, 12, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
    0, 0, 0, 31, 23, 0, 248, 167, 0, 16, 98, 141, 0, 160, 0, 143, 3, 128, 0, 0, 245, 245, 0, 0, 0,
    0, 3, 63,
];
const BROTLI_INVALID_HEADER_PATCH: &[u8] = &[
    66, 83, 68, 70, 50, 2, 2, 2, 12, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
    0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
];

const PUFFIN_FIXTURES: &str = "tests/fixtures/puffin";
const LZ4_FIXTURES: &str = "tests/fixtures/lz4";
const LZ4DIFF_FIXTURES: &str = "tests/fixtures/lz4diff";

#[cfg(otadump_zucchini)]
fn brotli_compress(bytes: &[u8]) -> Vec<u8> {
    let mut compressed = Vec::new();
    {
        let mut writer = brotli::CompressorWriter::new(&mut compressed, 4096, 9, 20);
        writer.write_all(bytes).unwrap();
    }
    compressed
}

#[cfg(otadump_zucchini)]
fn zucchini_brotli_patch(name: &str) -> Vec<u8> {
    let patch = fs::read(Path::new(ZUCCHINI_FIXTURES).join(format!("{name}.zuc"))).unwrap();
    brotli_compress(&patch)
}

#[cfg(otadump_zucchini)]
fn malformed_brotli_stream() -> Vec<u8> {
    b"not a Brotli stream\n".to_vec()
}

#[cfg(otadump_zucchini)]
fn malformed_inner_zucchini_patch() -> Vec<u8> {
    brotli_compress(b"not a zucchini patch")
}

#[cfg(otadump_zucchini)]
fn truncated_zucchini_patch(name: &str) -> Vec<u8> {
    let mut patch = zucchini_brotli_patch(name);
    patch.truncate(patch.len() - 1);
    patch
}

fn lz4_reference(name: &str) -> Vec<u8> {
    fs::read(Path::new(LZ4_FIXTURES).join(name)).unwrap()
}

fn lz4diff_fixture_case(name: &str) -> (Vec<u8>, Vec<u8>, Vec<u8>) {
    let patch = fs::read(Path::new(LZ4DIFF_FIXTURES).join(name).join("patch.lz4diff")).unwrap();
    let (source, target) = match name {
        "lz4-bsdiff" => {
            let block = lz4_reference("lz4-no-postfix.lz4");
            (block.clone(), block)
        }
        "lz4hc9-bsdiff" => {
            let block = lz4_reference("lz4hc9-no-postfix.lz4");
            (block.clone(), block)
        }
        "zero-padding-bsdiff" => {
            let block = lz4_reference("zero-padding-layout.lz4");
            (block.clone(), block)
        }
        "postfix-bsdiff" => {
            let source = lz4_reference("lz4-no-postfix.lz4");
            let mut target = source.clone();
            target[23] ^= 0x5a;
            (source, target)
        }
        "raw-puffdiff" => {
            let fixtures = Path::new(LZ4DIFF_FIXTURES).join(name);
            (
                fs::read(fixtures.join("source.bin")).unwrap(),
                fs::read(fixtures.join("target.bin")).unwrap(),
            )
        }
        _ => panic!("unknown LZ4DIFF fixture {name}"),
    };
    (source, target, patch)
}

fn run_lz4diff_bytes(
    source: &[u8],
    target: &[u8],
    patch: &[u8],
    operation_type: i32,
) -> Result<Vec<u8>, String> {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    fs::write(source_dir.join("system.img"), source).unwrap();

    let manifest = DeltaArchiveManifest {
        block_size: Some(1),
        minor_version: Some(9),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(source)),
            new_partition_info: Some(partition_info(target)),
            operations: vec![InstallOperation {
                operation_type,
                data_offset: Some(0),
                data_length: Some(patch.len() as u64),
                src_extents: vec![extent(0, source.len() as u64)],
                src_length: Some(source.len() as u64),
                dst_extents: vec![extent(0, target.len() as u64)],
                dst_length: Some(target.len() as u64),
                data_sha256_hash: Some(sha256(patch)),
                src_sha256_hash: Some(sha256(source)),
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, patch);

    match ExtractOptions::new().source_dir(&source_dir).extract(&payload, &output_dir) {
        Ok(()) => {
            assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
            assert_eq!(fs::read_dir(&output_dir).unwrap().count(), 1);
            Ok(fs::read(output_dir.join("system.img")).unwrap())
        }
        Err(error) => {
            assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
            assert!(!output_dir.join("system.img").exists());
            assert!(fs::read_dir(&output_dir).unwrap().next().is_none());
            Err(error.to_string())
        }
    }
}

fn run_lz4diff_extraction(name: &str, operation_type: i32) -> Result<Vec<u8>, String> {
    let (source, target, patch) = lz4diff_fixture_case(name);
    run_lz4diff_bytes(&source, &target, &patch, operation_type)
}

fn rewrite_lz4diff_header(patch: &[u8], change: impl FnOnce(&mut Lz4diffHeader)) -> Vec<u8> {
    let header_size = u32::from_be_bytes(patch[11..15].try_into().unwrap()) as usize;
    let mut header = Lz4diffHeader::decode(&patch[16..16 + header_size]).unwrap();
    change(&mut header);
    let header = header.encode_to_vec();
    let mut changed = Vec::with_capacity(16 + header.len() + patch.len() - 16 - header_size);
    changed.extend_from_slice(b"LZ4DIFF");
    changed.extend_from_slice(&1u32.to_be_bytes());
    changed.extend_from_slice(&(header.len() as u32).to_be_bytes());
    changed.push(0);
    changed.extend_from_slice(&header);
    changed.extend_from_slice(&patch[16 + header_size..]);
    changed
}

#[test]
fn lz4diff_operations_reconstruct_frozen_targets() {
    for (name, operation_type) in [
        ("lz4-bsdiff", 12),
        ("lz4hc9-bsdiff", 12),
        ("zero-padding-bsdiff", 12),
        ("postfix-bsdiff", 12),
        ("raw-puffdiff", 13),
    ] {
        let (_, expected, _) = lz4diff_fixture_case(name);
        let output = run_lz4diff_extraction(name, operation_type).unwrap();
        assert_eq!(output, expected, "fixture {name}");
    }
}

#[test]
fn malformed_lz4diff_data_fails_without_publication_or_process_failure() {
    let (source, target, valid) = lz4diff_fixture_case("postfix-bsdiff");

    let mut bad_magic = valid.clone();
    bad_magic[0] = b'X';
    let mut bad_version = valid.clone();
    bad_version[7..11].copy_from_slice(&2u32.to_be_bytes());
    let mut bad_padding = valid.clone();
    bad_padding[15] = 1;
    let mut overrun = valid.clone();
    overrun[11..15].copy_from_slice(&u32::MAX.to_be_bytes());
    let malformed_proto =
        [b"LZ4DIFF".as_slice(), &1u32.to_be_bytes(), &1u32.to_be_bytes(), &[0, 0x80]].concat();
    let mut nested_header = vec![0x23; 101];
    nested_header.extend(std::iter::repeat_n(0x24, 101));
    let mut excessive_nesting = Vec::new();
    excessive_nesting.extend_from_slice(b"LZ4DIFF");
    excessive_nesting.extend_from_slice(&1u32.to_be_bytes());
    excessive_nesting.extend_from_slice(&(nested_header.len() as u32).to_be_bytes());
    excessive_nesting.push(0);
    excessive_nesting.extend_from_slice(&nested_header);
    excessive_nesting.push(0);
    let unknown_algorithm = rewrite_lz4diff_header(&valid, |header| {
        header.dst_info.as_mut().unwrap().algo.as_mut().unwrap().algorithm_type = 99;
    });
    let missing_algorithm = rewrite_lz4diff_header(&valid, |header| {
        header.src_info.as_mut().unwrap().algo = None;
    });
    let bad_hc_level = rewrite_lz4diff_header(&valid, |header| {
        let algo = header.dst_info.as_mut().unwrap().algo.as_mut().unwrap();
        algo.algorithm_type = 2;
        algo.level = 13;
    });
    let unknown_inner = rewrite_lz4diff_header(&valid, |header| header.inner_type = 7);
    let unsorted = rewrite_lz4diff_header(&valid, |header| {
        header.src_info.as_mut().unwrap().block_info[0].uncompressed_offset = 1;
    });
    let out_of_bound = rewrite_lz4diff_header(&valid, |header| {
        header.src_info.as_mut().unwrap().block_info[0].uncompressed_length = u64::MAX;
    });
    let invalid_physical = rewrite_lz4diff_header(&valid, |header| {
        let block = &mut header.src_info.as_mut().unwrap().block_info[0];
        block.compressed_length = block.uncompressed_length + 1;
    });
    let short_hash = rewrite_lz4diff_header(&valid, |header| {
        header.dst_info.as_mut().unwrap().block_info[0].sha256_hash.pop();
    });
    let wrong_hash = rewrite_lz4diff_header(&valid, |header| {
        header.dst_info.as_mut().unwrap().block_info[0].sha256_hash[0] ^= 1;
    });
    let missing_postfix_hash = rewrite_lz4diff_header(&valid, |header| {
        header.dst_info.as_mut().unwrap().block_info[0].sha256_hash.clear();
    });
    let malformed_postfix = rewrite_lz4diff_header(&valid, |header| {
        header.dst_info.as_mut().unwrap().block_info[0].postfix_bspatch[0] = b'X';
    });
    let source_only_metadata = rewrite_lz4diff_header(&valid, |header| {
        header.src_info.as_mut().unwrap().block_info[0].sha256_hash = vec![0; 32];
    });

    for (patch, expected_error) in [
        (bad_magic, "invalid LZ4DIFF magic"),
        (bad_version, "unsupported LZ4DIFF version"),
        (bad_padding, "framing padding byte is not zero"),
        (overrun, "protobuf header exceeds the maximum size"),
        (malformed_proto, "truncated LZ4DIFF protobuf varint"),
        (excessive_nesting, "protobuf recursion limit exceeded"),
        (unknown_algorithm, "unknown LZ4DIFF destination compression algorithm"),
        (missing_algorithm, "LZ4DIFF source algorithm is missing"),
        (bad_hc_level, "LZ4HC level must be"),
        (unknown_inner, "unknown LZ4DIFF inner patch type"),
        (unsorted, "source blocks are not contiguous"),
        (out_of_bound, "source uncompressed stream exceeds"),
        (invalid_physical, "physical length exceeds its raw length"),
        (short_hash, "SHA-256 hash must be empty or 32 bytes"),
        (wrong_hash, "reference recompression hash mismatch"),
        (missing_postfix_hash, "postfix patch requires a SHA-256 hash"),
        (malformed_postfix, "postfix patch"),
        (source_only_metadata, "contains destination-only metadata"),
    ] {
        let error = run_lz4diff_bytes(&source, &target, &patch, 12).unwrap_err();
        assert!(error.contains(expected_error), "unexpected error: {error}");
    }

    let mismatched_inner = rewrite_lz4diff_header(&valid, |header| header.inner_type = 1);
    let error = run_lz4diff_bytes(&source, &target, &mismatched_inner, 12).unwrap_err();
    assert!(error.contains("operation type does not match"), "unexpected error: {error}");
}

fn run_puffdiff_extraction(source: &[u8], target: &[u8], patch: &[u8]) -> Result<Vec<u8>, String> {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();

    let source_split = source.len() / 2;
    let mut source_partition = Vec::with_capacity(source.len() + 1);
    source_partition.extend_from_slice(&source[..source_split]);
    source_partition.push(0xa5);
    source_partition.extend_from_slice(&source[source_split..]);
    fs::write(source_dir.join("system.img"), &source_partition).unwrap();

    let target_split = target.len() / 2;
    let manifest = DeltaArchiveManifest {
        block_size: Some(1),
        minor_version: Some(5),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(&source_partition)),
            new_partition_info: Some(partition_info(target)),
            operations: vec![InstallOperation {
                operation_type: 9,
                data_offset: Some(0),
                data_length: Some(patch.len() as u64),
                src_extents: vec![
                    extent(0, source_split as u64),
                    extent((source_split + 1) as u64, (source.len() - source_split) as u64),
                ],
                src_length: Some(source.len() as u64),
                dst_extents: vec![
                    extent(0, target_split as u64),
                    extent(target_split as u64, (target.len() - target_split) as u64),
                ],
                dst_length: Some(target.len() as u64),
                data_sha256_hash: Some(sha256(patch)),
                src_sha256_hash: Some(sha256(source)),
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, patch);

    match ExtractOptions::new()
        .source_dir(&source_dir)
        .num_threads(2)
        .extract(&payload, &output_dir)
    {
        Ok(()) => {
            assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source_partition);
            assert_eq!(fs::read_dir(&output_dir).unwrap().count(), 1);
            Ok(fs::read(output_dir.join("system.img")).unwrap())
        }
        Err(error) => {
            assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source_partition);
            assert!(!output_dir.join("system.img").exists());
            assert!(fs::read_dir(&output_dir).unwrap().next().is_none());
            Err(error.to_string())
        }
    }
}

fn puffin_fixture(name: &str) -> Vec<u8> {
    fs::read(Path::new(PUFFIN_FIXTURES).join(name)).unwrap()
}

fn with_puffin_patch_type(patch: &[u8], patch_type: u8) -> Vec<u8> {
    let header_len = u32::from_be_bytes(patch[4..8].try_into().unwrap()) as usize;
    let mut changed = Vec::with_capacity(patch.len() + 2);
    changed.extend_from_slice(&patch[..8 + header_len]);
    changed.extend_from_slice(&[0x20, patch_type]);
    changed.extend_from_slice(&patch[8 + header_len..]);
    changed[4..8].copy_from_slice(&((header_len + 2) as u32).to_be_bytes());
    changed
}

#[test]
fn puffdiff_bsdiff_reconstructs_pinned_puffin_goldens() {
    let source = puffin_fixture("deflates-sample1.bin");
    for (patch_name, target_name) in [
        ("patch-1-to-2.puf", "deflates-sample2.bin"),
        ("patch-1-to-raw.puf", "raw-11-22-33-44.bin"),
    ] {
        let patch = puffin_fixture(patch_name);
        let target = puffin_fixture(target_name);
        let output = run_puffdiff_extraction(&source, &target, &patch).unwrap();
        assert_eq!(output, target);
    }
}

#[test]
#[cfg(otadump_zucchini)]
fn puffdiff_zucchini_reconstructs_pinned_puffin_golden() {
    let source = puffin_fixture("deflates-sample1.bin");
    let target = puffin_fixture("deflates-sample2.bin");
    let patch = puffin_fixture("patch-1-to-2-zucchini.puf");

    let output = run_puffdiff_extraction(&source, &target, &patch).unwrap();

    assert_eq!(output, target);
}

#[test]
fn malformed_puffdiff_data_fails_without_publication_or_process_failure() {
    let source = puffin_fixture("deflates-sample1.bin");
    let target = puffin_fixture("deflates-sample2.bin");
    let valid_patch = puffin_fixture("patch-1-to-2.puf");

    let mut bad_magic = valid_patch.clone();
    bad_magic[..4].copy_from_slice(b"BAD!");

    let truncated_proto = [b"PUF1".as_slice(), &1u32.to_be_bytes(), &[0x80]].concat();

    let mut non_byte_puff = valid_patch.clone();
    let puff_length = non_byte_puff
        .windows(6)
        .position(|window| window == [0x12, 0x04, 0x08, 0x10, 0x10, 0x58])
        .unwrap()
        + 5;
    non_byte_puff[puff_length] += 1;

    let mut overlapping_deflates = valid_patch.clone();
    let second_deflate_offset = overlapping_deflates
        .windows(6)
        .position(|window| window == [0x0a, 0x04, 0x08, 0x50, 0x10, 0x0a])
        .unwrap()
        + 3;
    overlapping_deflates[second_deflate_offset] = 0x40;

    let mut bad_inner_bsdiff = valid_patch.clone();
    let header_len = u32::from_be_bytes(bad_inner_bsdiff[4..8].try_into().unwrap()) as usize;
    bad_inner_bsdiff[8 + header_len] = b'X';

    for (patch, expected_error) in [
        (bad_magic, "missing PUF1 magic"),
        (truncated_proto, "truncated protobuf varint"),
        (non_byte_puff, "puff extent is not byte-aligned"),
        (overlapping_deflates, "deflate extents overlap or are unsorted"),
        (bad_inner_bsdiff, "inner BSDIFF patch is invalid"),
        (with_puffin_patch_type(&valid_patch, 2), "unsupported PUFFDIFF patch type 2"),
    ] {
        let error = run_puffdiff_extraction(&source, &target, &patch).unwrap_err();
        assert!(error.contains(expected_error), "unexpected error: {error}");
    }

    let short_target = &target[..target.len() - 1];
    let error = run_puffdiff_extraction(&source, short_target, &valid_patch).unwrap_err();
    assert!(error.contains("destination raw size mismatch"), "unexpected error: {error}");
}

#[test]
#[cfg(otadump_zucchini)]
fn malformed_puffdiff_zucchini_fails_without_publication_or_process_failure() {
    let source = puffin_fixture("deflates-sample1.bin");
    let target = puffin_fixture("deflates-sample2.bin");
    let valid_patch = puffin_fixture("patch-1-to-2-zucchini.puf");
    let malformed_zucchini = malformed_inner_zucchini_patch();

    for (patch, expected_error) in [
        (
            with_puffin_inner_patch(&valid_patch, b"not a Brotli stream\n"),
            "Unable to decode ZUCCHINI Brotli patch",
        ),
        (
            with_puffin_inner_patch(&valid_patch, &malformed_zucchini),
            "inner ZUCCHINI patch is invalid: apply failed: invalid ensemble patch",
        ),
    ] {
        let error = run_puffdiff_extraction(&source, &target, &patch).unwrap_err();
        assert!(error.contains(expected_error), "unexpected error: {error}");
    }
}

#[cfg(otadump_zucchini)]
const ZUCCHINI_FIXTURES: &str = "tests/fixtures/zucchini";

#[cfg(otadump_zucchini)]
fn assert_zucchini_fixture(name: &str, extension: &str) {
    let fixtures = Path::new(ZUCCHINI_FIXTURES);
    let old = fs::read(fixtures.join(format!("{name}-old{extension}"))).unwrap();
    let expected = fs::read(fixtures.join(format!("{name}-new{extension}"))).unwrap();
    let patch = fs::read(fixtures.join(format!("{name}.zuc"))).unwrap();
    let output = otadump::zucchini::apply(&old, &patch, expected.len()).unwrap();
    assert_eq!(output, expected);
}

#[cfg(otadump_zucchini)]
fn assert_zucchini_extraction(name: &str, extension: &str) {
    let fixtures = Path::new(ZUCCHINI_FIXTURES);
    let old = fs::read(fixtures.join(format!("{name}-old{extension}"))).unwrap();
    let target = fs::read(fixtures.join(format!("{name}-new{extension}"))).unwrap();
    let patch = zucchini_brotli_patch(name);
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();

    let old_split = old.len() / 2;
    let mut source = Vec::with_capacity(old.len() + 1);
    source.extend_from_slice(&old[..old_split]);
    source.push(0xa5);
    source.extend_from_slice(&old[old_split..]);
    fs::write(source_dir.join("system.img"), &source).unwrap();

    let target_split = target.len() / 2;
    let mut expected = Vec::with_capacity(target.len() + 1);
    expected.extend_from_slice(&target[..target_split]);
    expected.push(0);
    expected.extend_from_slice(&target[target_split..]);
    let manifest = DeltaArchiveManifest {
        block_size: Some(1),
        minor_version: Some(8),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(&source)),
            new_partition_info: Some(partition_info(&expected)),
            operations: vec![InstallOperation {
                operation_type: 11,
                data_offset: Some(0),
                data_length: Some(patch.len() as u64),
                src_extents: vec![
                    extent(0, old_split as u64),
                    extent((old_split + 1) as u64, (old.len() - old_split) as u64),
                ],
                src_length: Some(old.len() as u64),
                dst_extents: vec![
                    extent(0, target_split as u64),
                    extent((target_split + 1) as u64, (target.len() - target_split) as u64),
                ],
                dst_length: Some(target.len() as u64),
                data_sha256_hash: Some(sha256(&patch)),
                src_sha256_hash: Some(sha256(&old)),
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &patch);

    ExtractOptions::new()
        .source_dir(&source_dir)
        .num_threads(2)
        .extract(&payload, &output_dir)
        .unwrap();

    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), expected);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
    assert_eq!(fs::read_dir(&output_dir).unwrap().count(), 1);
}

#[cfg(otadump_zucchini)]
fn assert_zucchini_extraction_fails(patch: &[u8], expected_error: &str) {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let source = b"abcd";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(1),
        minor_version: Some(8),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(source)),
            new_partition_info: Some(partition_info(source)),
            operations: vec![InstallOperation {
                operation_type: 11,
                data_offset: Some(0),
                data_length: Some(patch.len() as u64),
                src_extents: vec![extent(0, source.len() as u64)],
                src_length: Some(source.len() as u64),
                dst_extents: vec![extent(0, source.len() as u64)],
                dst_length: Some(source.len() as u64),
                data_sha256_hash: Some(sha256(patch)),
                src_sha256_hash: Some(sha256(source)),
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, patch);

    let error = ExtractOptions::new()
        .source_dir(&source_dir)
        .num_threads(2)
        .extract(&payload, &output_dir)
        .unwrap_err()
        .to_string();

    assert!(error.contains(expected_error), "unexpected error: {error}");
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
    assert!(!output_dir.join("system.img").exists());
    assert!(fs::read_dir(&output_dir).unwrap().next().is_none());
}

#[test]
#[cfg(otadump_zucchini)]
fn zucchini_wrapper_applies_android_formats_exactly() {
    assert_zucchini_fixture("noop", ".bin");
    assert_zucchini_fixture("dex", ".dex");
    assert_zucchini_fixture("elf-x86", "");
    assert_zucchini_fixture("elf", "");
    assert_zucchini_fixture("elf-arm32", "");
    assert_zucchini_fixture("elf-arm64", "");
}

#[test]
#[cfg(otadump_zucchini)]
fn zucchini_operations_reconstruct_android_formats_exactly() {
    for (name, extension) in [
        ("noop", ".bin"),
        ("dex", ".dex"),
        ("elf-x86", ""),
        ("elf", ""),
        ("elf-arm32", ""),
        ("elf-arm64", ""),
    ] {
        assert_zucchini_extraction(name, extension);
    }
}

#[test]
#[cfg(otadump_zucchini)]
fn zucchini_operation_rejects_malformed_outer_brotli_without_publication() {
    for patch in [malformed_brotli_stream(), truncated_zucchini_patch("noop")] {
        assert_zucchini_extraction_fails(&patch, "Unable to decode ZUCCHINI Brotli patch");
    }
}

#[test]
#[cfg(otadump_zucchini)]
fn zucchini_operation_rejects_malformed_inner_patch_without_publication() {
    let malformed = malformed_inner_zucchini_patch();
    assert_zucchini_extraction_fails(&malformed, "ZUCCHINI apply failed: invalid ensemble patch");
}

#[test]
#[cfg(otadump_zucchini)]
fn zucchini_wrapper_applies_large_dex_jumbo_reference() {
    assert_zucchini_fixture("dex-large", ".dex");
}

#[test]
#[cfg(otadump_zucchini)]
fn zucchini_wrapper_rejects_unsafe_large_dex_string16_reference() {
    let fixtures = Path::new(ZUCCHINI_FIXTURES);
    let old = fs::read(fixtures.join("dex-large-old.dex")).unwrap();
    let patch = fs::read(fixtures.join("dex-large-unsafe16.zuc")).unwrap();
    let expected_size = fs::metadata(fixtures.join("dex-large-new.dex")).unwrap().len() as usize;
    let error = otadump::zucchini::apply(&old, &patch, expected_size).unwrap_err();
    assert_eq!(error.status(), otadump::zucchini::Status::ApplyError);
    assert_eq!(error.to_string(), "android executable preflight failed");
}

#[test]
#[cfg(otadump_zucchini)]
fn zucchini_wrapper_returns_owned_error_for_malformed_patch() {
    let error = otadump::zucchini::apply(b"abcd", b"not a patch", 5).unwrap_err();
    assert_eq!(error.status(), otadump::zucchini::Status::InvalidPatch);
    assert_eq!(error.to_string(), "invalid ensemble patch");
}

fn extent(start_block: u64, num_blocks: u64) -> Extent {
    Extent { start_block: Some(start_block), num_blocks: Some(num_blocks) }
}

fn write_payload(path: &Path, manifest: DeltaArchiveManifest, data: &[u8]) {
    let manifest = manifest.encode_to_vec();
    let mut payload = Vec::with_capacity(24 + manifest.len() + data.len());
    payload.extend_from_slice(b"CrAU");
    payload.extend_from_slice(&2u64.to_be_bytes());
    payload.extend_from_slice(&(manifest.len() as u64).to_be_bytes());
    payload.extend_from_slice(&0u32.to_be_bytes());
    payload.extend_from_slice(&manifest);
    payload.extend_from_slice(data);
    fs::write(path, payload).unwrap();
}

fn partition_info(bytes: &[u8]) -> PartitionInfo {
    PartitionInfo { size: Some(bytes.len() as u64), hash: Some(sha256(bytes)) }
}

#[test]
fn source_copy_reconstructs_noncontiguous_extents_without_modifying_source() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let source = b"AAAABBBBCCCCDDDD";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let expected = b"AAAACCCC";
    let operation = InstallOperation {
        operation_type: 4,
        src_extents: vec![extent(2, 1), extent(0, 1)],
        src_length: Some(8),
        dst_extents: vec![extent(1, 1), extent(0, 1)],
        dst_length: Some(8),
        src_sha256_hash: Some(sha256(b"CCCCAAAA")),
        ..Default::default()
    };
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(source)),
            new_partition_info: Some(partition_info(expected)),
            operations: vec![operation],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    ExtractOptions::new()
        .source_dir(&source_dir)
        .num_threads(2)
        .extract(&payload, &output_dir)
        .unwrap();

    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), expected);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
}

#[test]
fn source_bsdiff_reconstructs_bsdiff40_without_modifying_source() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let source = b"abcdefgh";
    let expected = b"abXYefgh";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(1),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(source)),
            new_partition_info: Some(partition_info(expected)),
            operations: vec![InstallOperation {
                operation_type: 5,
                data_offset: Some(0),
                data_length: Some(BSDIFF40_PATCH.len() as u64),
                src_extents: vec![extent(0, source.len() as u64)],
                src_length: Some(source.len() as u64),
                dst_extents: vec![extent(0, expected.len() as u64)],
                dst_length: Some(expected.len() as u64),
                data_sha256_hash: Some(sha256(BSDIFF40_PATCH)),
                src_sha256_hash: Some(sha256(source)),
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, BSDIFF40_PATCH);

    ExtractOptions::new()
        .source_dir(&source_dir)
        .num_threads(2)
        .extract(&payload, &output_dir)
        .unwrap();

    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), expected);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
}

#[test]
fn brotli_bsdiff_reconstructs_bsdf2_without_modifying_source() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let source = b"abcdefgh";
    let expected = b"abXYefgh";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(1),
        minor_version: Some(4),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(source)),
            new_partition_info: Some(partition_info(expected)),
            operations: vec![InstallOperation {
                operation_type: 10,
                data_offset: Some(0),
                data_length: Some(BROTLI_BSDF2_PATCH.len() as u64),
                src_extents: vec![extent(0, source.len() as u64)],
                src_length: Some(source.len() as u64),
                dst_extents: vec![extent(0, expected.len() as u64)],
                dst_length: Some(expected.len() as u64),
                data_sha256_hash: Some(sha256(BROTLI_BSDF2_PATCH)),
                src_sha256_hash: Some(sha256(source)),
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, BROTLI_BSDF2_PATCH);

    ExtractOptions::new()
        .source_dir(&source_dir)
        .num_threads(2)
        .extract(&payload, &output_dir)
        .unwrap();

    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), expected);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
}

#[test]
fn uncompressed_bsdf2_negative_seek_adds_diff_byte() {
    let mut patch = Vec::new();
    // BSDF2 magic + uncompressed flags (0 for control, diff, extra)
    patch.extend_from_slice(b"BSDF2\x00\x00\x00");
    patch.extend_from_slice(&72u64.to_le_bytes()); // control stream len: 3 tuples * 24
    patch.extend_from_slice(&3u64.to_le_bytes()); // diff stream len: 3
    patch.extend_from_slice(&3u64.to_le_bytes()); // new_size: 3

    // Tuple 1: add=1, copy=0, seek=-2 (in-bounds source addition at oldpos=0; seek to -1)
    patch.extend_from_slice(&1u64.to_le_bytes());
    patch.extend_from_slice(&0u64.to_le_bytes());
    let seek_neg2: u64 = 2 | (1 << 63); // offtin sign-magnitude -2
    patch.extend_from_slice(&seek_neg2.to_le_bytes());

    // Tuple 2: add=1, copy=0, seek=10 (negative oldpos=-1 treated as zero; seek to 10)
    patch.extend_from_slice(&1u64.to_le_bytes());
    patch.extend_from_slice(&0u64.to_le_bytes());
    patch.extend_from_slice(&10u64.to_le_bytes());

    // Tuple 3: add=1, copy=0, seek=0 (out-of-range oldpos=10 treated as zero)
    patch.extend_from_slice(&1u64.to_le_bytes());
    patch.extend_from_slice(&0u64.to_le_bytes());
    patch.extend_from_slice(&0u64.to_le_bytes());

    // Diff stream: 3 bytes
    let diff_byte1: u8 = 0x01;
    let diff_byte2: u8 = 0x42;
    let diff_byte3: u8 = 0x24;
    patch.push(diff_byte1);
    patch.push(diff_byte2);
    patch.push(diff_byte3);

    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let source = b"Z";
    fs::write(source_dir.join("system.img"), source).unwrap();

    let expected = [b'Z'.wrapping_add(diff_byte1), diff_byte2, diff_byte3];
    let manifest = DeltaArchiveManifest {
        block_size: Some(1),
        minor_version: Some(4),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(source)),
            new_partition_info: Some(partition_info(&expected)),
            operations: vec![InstallOperation {
                operation_type: 5, // SOURCE_BSDIFF
                data_offset: Some(0),
                data_length: Some(patch.len() as u64),
                src_extents: vec![extent(0, source.len() as u64)],
                src_length: Some(source.len() as u64),
                dst_extents: vec![extent(0, expected.len() as u64)],
                dst_length: Some(expected.len() as u64),
                data_sha256_hash: Some(sha256(&patch)),
                src_sha256_hash: Some(sha256(source)),
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &patch);

    ExtractOptions::new()
        .source_dir(&source_dir)
        .num_threads(1)
        .extract(&payload, &output_dir)
        .unwrap();

    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), expected);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
}

#[test]
fn malformed_bsdiff_headers_fail_cleanly_and_remove_staging() {
    for (operation_type, patch, expected_error) in [
        (5, &[0; 32][..], "SOURCE_BSDIFF patch is invalid"),
        (10, BROTLI_INVALID_HEADER_PATCH, "BROTLI_BSDIFF patch is invalid"),
    ] {
        let temporary = TempDir::new().unwrap();
        let source_dir = temporary.path().join("source");
        let output_dir = temporary.path().join("output");
        fs::create_dir(&source_dir).unwrap();
        let source = b"abcdefgh";
        fs::write(source_dir.join("system.img"), source).unwrap();
        let manifest = DeltaArchiveManifest {
            block_size: Some(1),
            minor_version: Some(4),
            partitions: vec![PartitionUpdate {
                partition_name: "system".into(),
                old_partition_info: Some(partition_info(source)),
                new_partition_info: Some(partition_info(b"abXYefgh")),
                operations: vec![InstallOperation {
                    operation_type,
                    data_offset: Some(0),
                    data_length: Some(patch.len() as u64),
                    src_extents: vec![extent(0, source.len() as u64)],
                    src_length: Some(source.len() as u64),
                    dst_extents: vec![extent(0, source.len() as u64)],
                    dst_length: Some(source.len() as u64),
                    data_sha256_hash: Some(sha256(patch)),
                    src_sha256_hash: Some(sha256(source)),
                }],
                ..Default::default()
            }],
        };
        let payload = temporary.path().join("payload.bin");
        write_payload(&payload, manifest, patch);

        let error = ExtractOptions::new()
            .source_dir(&source_dir)
            .num_threads(2)
            .extract(&payload, &output_dir)
            .unwrap_err()
            .to_string();

        assert!(error.contains(expected_error), "unexpected error: {error}");
        assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
        assert!(!output_dir.join("system.img").exists());
        assert!(fs::read_dir(&output_dir).unwrap().next().is_none());
    }
}

#[test]
fn source_validation_rejects_wrong_base_before_creating_output() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    fs::write(source_dir.join("boot.img"), b"bad!").unwrap();
    let operation = InstallOperation {
        operation_type: 4,
        src_extents: vec![extent(0, 1)],
        dst_extents: vec![extent(0, 1)],
        ..Default::default()
    };
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "boot".into(),
            old_partition_info: Some(partition_info(b"good")),
            new_partition_info: Some(partition_info(b"good")),
            operations: vec![operation],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let error = ExtractOptions::new()
        .source_dir(&source_dir)
        .extract(&payload, &output_dir)
        .unwrap_err()
        .to_string();

    assert!(error.contains("Source partition hash mismatch"));
    assert!(!output_dir.join("boot.img").exists());
}

#[test]
fn padded_source_uses_declared_prefix_without_modifying_tail() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let declared_source = b"base";
    let source = b"basefooter";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(declared_source)),
            new_partition_info: Some(partition_info(declared_source)),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(0, 1)],
                src_length: Some(4),
                dst_extents: vec![extent(0, 1)],
                dst_length: Some(4),
                src_sha256_hash: Some(sha256(declared_source)),
                ..Default::default()
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    ExtractOptions::new().source_dir(&source_dir).extract(&payload, &output_dir).unwrap();

    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), declared_source);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
}

#[test]
fn source_shorter_than_declared_size_fails_cleanly() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let source = b"bas";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let declared_source = b"base";
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(declared_source)),
            new_partition_info: Some(partition_info(declared_source)),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(0, 1)],
                dst_extents: vec![extent(0, 1)],
                ..Default::default()
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let error = ExtractOptions::new()
        .source_dir(&source_dir)
        .extract(&payload, &output_dir)
        .unwrap_err()
        .to_string();

    assert!(error.contains("Source partition size mismatch"), "unexpected error: {error}");
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
    assert!(!output_dir.join("system.img").exists());
}

#[test]
fn source_extent_cannot_enter_padding_beyond_declared_size() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let declared_source = b"base";
    let source = b"basefoot";
    fs::write(source_dir.join("system.img"), source).unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(declared_source)),
            new_partition_info: Some(partition_info(declared_source)),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(1, 1)],
                src_length: Some(4),
                dst_extents: vec![extent(0, 1)],
                dst_length: Some(4),
                src_sha256_hash: Some(sha256(b"foot")),
                ..Default::default()
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let error = ExtractOptions::new()
        .source_dir(&source_dir)
        .extract(&payload, &output_dir)
        .unwrap_err()
        .to_string();

    assert!(error.contains("Invalid source extents"), "unexpected error: {error}");
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
    assert!(!output_dir.join("system.img").exists());
}

#[test]
fn delta_operation_without_source_directory_fails_clearly() {
    let temporary = TempDir::new().unwrap();
    let output_dir = temporary.path().join("output");
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "boot".into(),
            old_partition_info: Some(partition_info(b"base")),
            new_partition_info: Some(partition_info(b"base")),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(0, 1)],
                dst_extents: vec![extent(0, 1)],
                ..Default::default()
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let error = ExtractOptions::new().extract(&payload, &output_dir).unwrap_err().to_string();

    assert!(error.contains("require a source directory"));
    assert!(!output_dir.join("boot.img").exists());
}

#[test]
fn malformed_partition_layouts_fail_without_escaping_or_leaving_partial_images() {
    for (name, operations, expected_error) in [
        (
            "../escape",
            vec![InstallOperation {
                operation_type: 0,
                data_offset: Some(0),
                data_length: Some(4),
                dst_extents: vec![extent(0, 1)],
                ..Default::default()
            }],
            "Unsafe partition name",
        ),
        (
            "system",
            vec![
                InstallOperation {
                    operation_type: 0,
                    data_offset: Some(0),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                },
                InstallOperation {
                    operation_type: 0,
                    data_offset: Some(4),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                },
            ],
            "Destination extents overlap",
        ),
    ] {
        let temporary = TempDir::new().unwrap();
        let output_dir = temporary.path().join("output");
        let target = b"data";
        let manifest = DeltaArchiveManifest {
            block_size: Some(4),
            minor_version: Some(0),
            partitions: vec![PartitionUpdate {
                partition_name: name.into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(target)),
                operations,
                ..Default::default()
            }],
        };
        let payload = temporary.path().join("payload.bin");
        write_payload(&payload, manifest, b"datadata");

        let error = ExtractOptions::new().extract(&payload, &output_dir).unwrap_err().to_string();

        assert!(error.contains(expected_error), "unexpected error: {error}");
        assert!(!temporary.path().join("escape.img").exists());
        assert!(!output_dir.join("system.img").exists());
    }
}

#[test]
fn full_replace_payload_remains_compatible() {
    let temporary = TempDir::new().unwrap();
    let output_dir = temporary.path().join("output");
    let expected = b"full payload data";
    let operation = InstallOperation {
        operation_type: 0,
        data_offset: Some(0),
        data_length: Some(expected.len() as u64),
        dst_extents: vec![extent(0, 2)],
        data_sha256_hash: Some(sha256(expected)),
        ..Default::default()
    };
    let mut padded = expected.to_vec();
    padded.resize(32, 0);
    let manifest = DeltaArchiveManifest {
        block_size: Some(16),
        minor_version: Some(0),
        partitions: vec![PartitionUpdate {
            partition_name: "vendor".into(),
            old_partition_info: None,
            new_partition_info: Some(partition_info(&padded)),
            operations: vec![operation],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, expected);

    ExtractOptions::new().extract(&payload, &output_dir).unwrap();

    assert_eq!(fs::read(output_dir.join("vendor.img")).unwrap(), padded);
}

#[test]
fn omitted_verity_tree_is_generated_in_aosp_top_down_order() {
    const LEAF_HASHES: [[u8; 32]; 5] = [
        [
            0x2b, 0xbf, 0x03, 0x32, 0xe3, 0x58, 0xa6, 0xa5, 0xdd, 0xc7, 0x3e, 0xa7, 0x1e, 0x75,
            0xdc, 0x83, 0xf5, 0x8f, 0xec, 0xfc, 0x25, 0x4a, 0x4e, 0x7d, 0x41, 0x33, 0x86, 0x95,
            0x8b, 0xd9, 0xe0, 0x00,
        ],
        [
            0x24, 0x59, 0x0e, 0xd6, 0xcb, 0x84, 0x1e, 0xa2, 0xe5, 0xd8, 0x39, 0xe7, 0xc6, 0x3d,
            0xb6, 0x9b, 0x75, 0x50, 0xb4, 0x88, 0x60, 0x7a, 0xf2, 0x52, 0x75, 0x53, 0x0a, 0x5e,
            0x62, 0xce, 0x21, 0x7c,
        ],
        [
            0xf1, 0x06, 0x4b, 0x13, 0x33, 0x00, 0xf3, 0x86, 0x53, 0x23, 0x3e, 0x15, 0x04, 0x99,
            0x74, 0x81, 0xa0, 0x0b, 0xa8, 0xa1, 0x17, 0xd2, 0x0e, 0xd6, 0xae, 0x58, 0xc6, 0x75,
            0x8e, 0x69, 0x39, 0xcc,
        ],
        [
            0xda, 0x97, 0xb2, 0x05, 0xf9, 0xe7, 0xa3, 0xad, 0x12, 0x0d, 0xf3, 0xb2, 0x03, 0x14,
            0xe2, 0x07, 0x1b, 0xb0, 0xfb, 0x0f, 0x87, 0x0f, 0x95, 0x21, 0xe0, 0xb2, 0xf9, 0x89,
            0x1e, 0xe6, 0x9b, 0xe8,
        ],
        [
            0xa7, 0xd9, 0xa0, 0xf7, 0xbf, 0xe5, 0xfa, 0x24, 0x7c, 0x32, 0x31, 0x87, 0x01, 0x9d,
            0x01, 0x25, 0xf6, 0x93, 0xf0, 0xcd, 0xf4, 0x70, 0x93, 0xa2, 0xf1, 0x39, 0x2b, 0x3f,
            0x57, 0xb9, 0xfb, 0x0b,
        ],
    ];
    const UPPER_HASHES: [[u8; 32]; 2] = [
        [
            0x73, 0x55, 0xdf, 0xc2, 0xeb, 0x76, 0xd2, 0xb4, 0x0d, 0x27, 0xe3, 0x8c, 0x41, 0x40,
            0x35, 0xa2, 0x7c, 0x5a, 0x8c, 0x95, 0x90, 0x2d, 0xdf, 0x77, 0xbb, 0x87, 0x69, 0x46,
            0x96, 0xd6, 0x1b, 0x91,
        ],
        [
            0xfe, 0xb1, 0x40, 0xb5, 0x15, 0x40, 0xbf, 0x36, 0x30, 0x8d, 0xce, 0x5c, 0x31, 0x08,
            0x45, 0xe4, 0x12, 0x51, 0x2e, 0xc6, 0x53, 0xf9, 0x2b, 0x4e, 0x31, 0x09, 0x30, 0x7f,
            0xab, 0x5e, 0x16, 0xe1,
        ],
    ];

    let temporary = TempDir::new().unwrap();
    let output_dir = temporary.path().join("output");
    let block_size = 128usize;
    let mut data = Vec::with_capacity(5 * block_size);
    for byte in [0x11, 0x22, 0x33, 0x44, 0x55] {
        data.extend(std::iter::repeat_n(byte, block_size));
    }
    let mut expected_tree = Vec::with_capacity(3 * block_size);
    expected_tree.extend(UPPER_HASHES.into_iter().flatten());
    expected_tree.resize(block_size, 0);
    expected_tree.extend(LEAF_HASHES[..4].iter().flatten());
    expected_tree.extend(LEAF_HASHES[4]);
    expected_tree.resize(3 * block_size, 0);
    let mut expected = data.clone();
    expected.extend_from_slice(&expected_tree);
    let manifest = DeltaArchiveManifest {
        block_size: Some(block_size as u32),
        minor_version: Some(6),
        partitions: vec![PartitionUpdate {
            partition_name: "vendor".into(),
            old_partition_info: None,
            new_partition_info: Some(partition_info(&expected)),
            operations: vec![InstallOperation {
                operation_type: 0,
                data_offset: Some(0),
                data_length: Some(data.len() as u64),
                dst_extents: vec![extent(0, 5)],
                dst_length: Some(data.len() as u64),
                data_sha256_hash: Some(sha256(&data)),
                ..Default::default()
            }],
            hash_tree_data_extent: Some(extent(0, 5)),
            hash_tree_extent: Some(extent(5, 3)),
            hash_tree_algorithm: Some("sha256".into()),
            hash_tree_salt: Some(b"verity-test-salt".to_vec()),
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &data);

    ExtractOptions::new().num_threads(4).extract(&payload, &output_dir).unwrap();

    let actual = fs::read(output_dir.join("vendor.img")).unwrap();
    assert_eq!(&actual[5 * block_size..], expected_tree);
    assert_eq!(actual, expected);
}

#[test]
fn malformed_verity_layouts_fail_without_leaving_staging_files() {
    for (tree_extent, operations, expected_error) in [
        (
            extent(5, 2),
            vec![InstallOperation {
                operation_type: 0,
                data_offset: Some(0),
                data_length: Some(5 * 128),
                dst_extents: vec![extent(0, 5)],
                ..Default::default()
            }],
            "Hash tree size mismatch",
        ),
        (
            extent(5, 3),
            vec![
                InstallOperation {
                    operation_type: 0,
                    data_offset: Some(0),
                    data_length: Some(5 * 128),
                    dst_extents: vec![extent(0, 5)],
                    ..Default::default()
                },
                InstallOperation {
                    operation_type: 6,
                    dst_extents: vec![extent(5, 1)],
                    ..Default::default()
                },
            ],
            "Hash tree extent overlaps destination extents",
        ),
    ] {
        let temporary = TempDir::new().unwrap();
        let output_dir = temporary.path().join("output");
        let data = vec![0x5a; 5 * 128];
        let manifest = DeltaArchiveManifest {
            block_size: Some(128),
            minor_version: Some(6),
            partitions: vec![PartitionUpdate {
                partition_name: "vendor".into(),
                new_partition_info: Some(partition_info(&vec![0; 8 * 128])),
                operations,
                hash_tree_data_extent: Some(extent(0, 5)),
                hash_tree_extent: Some(tree_extent),
                hash_tree_algorithm: Some("sha256".into()),
                hash_tree_salt: Some(vec![0x23; 32]),
                ..Default::default()
            }],
        };
        let payload = temporary.path().join("payload.bin");
        write_payload(&payload, manifest, &data);

        let error = ExtractOptions::new().extract(&payload, &output_dir).unwrap_err().to_string();

        assert!(error.contains(expected_error), "unexpected error: {error}");
        assert!(!output_dir.join("vendor.img").exists());
        assert!(fs::read_dir(&output_dir).unwrap().next().is_none());
    }
}

#[test]
fn fec_extents_match_android_reference_vectors() {
    for (blocks, fixture, roots) in
        [(1usize, "fec-one-block.bin", None), (300usize, "fec-300-block.bin", Some(2))]
    {
        let temporary = TempDir::new().unwrap();
        let output_dir = temporary.path().join("output");
        let data = if blocks == 1 {
            vec![1; 4096]
        } else {
            (0..blocks * 4096)
                .map(|index| ((index % 4096) * 37 + (index / 4096) * 53 + 13) as u8)
                .collect()
        };
        let fec = fs::read(Path::new("tests/fixtures/fec").join(fixture)).unwrap();
        let mut target = data.clone();
        target.extend_from_slice(&fec);
        let manifest = DeltaArchiveManifest {
            block_size: Some(4096),
            minor_version: Some(6),
            partitions: vec![PartitionUpdate {
                partition_name: "vendor".into(),
                new_partition_info: Some(partition_info(&target)),
                operations: vec![InstallOperation {
                    operation_type: 0,
                    data_offset: Some(0),
                    data_length: Some(data.len() as u64),
                    dst_extents: vec![extent(0, blocks as u64)],
                    ..Default::default()
                }],
                fec_data_extent: Some(extent(0, blocks as u64)),
                fec_extent: Some(extent(blocks as u64, (fec.len() / 4096) as u64)),
                fec_roots: roots,
                ..Default::default()
            }],
        };
        let payload = temporary.path().join("payload.bin");
        write_payload(&payload, manifest, &data);

        ExtractOptions::new().extract(&payload, &output_dir).unwrap();

        assert_eq!(fs::read(output_dir.join("vendor.img")).unwrap(), target);
        assert_eq!(fs::read_dir(&output_dir).unwrap().count(), 1);
    }
}

#[test]
fn malformed_fec_metadata_fails_without_publishing_an_image() {
    for (
        data_extent,
        storage_extent,
        roots,
        partition_blocks,
        operation_blocks,
        hash_tree,
        error,
    ) in [
        (Some(extent(0, 1)), None, Some(2), 3, 1, false, "FEC data and storage"),
        (Some(extent(0, 1)), Some(extent(1, 2)), Some(0), 3, 1, false, "FEC roots"),
        (Some(extent(0, 1)), Some(extent(1, 2)), Some(255), 3, 1, false, "FEC roots"),
        (Some(extent(0, 1)), Some(extent(1, 1)), Some(2), 2, 1, false, "FEC size mismatch"),
        (
            Some(extent(0, 1)),
            Some(extent(0, 2)),
            Some(2),
            2,
            1,
            false,
            "FEC storage extent must follow",
        ),
        (
            Some(extent(2, 1)),
            Some(extent(0, 2)),
            Some(2),
            3,
            1,
            false,
            "FEC storage extent must follow",
        ),
        (
            Some(extent(0, 1)),
            Some(extent(2, 2)),
            Some(2),
            3,
            1,
            false,
            "FEC storage extent exceeds partition size",
        ),
        (
            Some(extent(0, 1)),
            Some(extent(1, 2)),
            Some(2),
            3,
            3,
            false,
            "FEC storage extent overlaps destination extents",
        ),
        (
            Some(extent(0, 1)),
            Some(extent(1, 2)),
            Some(2),
            3,
            1,
            true,
            "FEC storage extent overlaps hash tree extent",
        ),
        (
            Some(extent(0, 1)),
            Some(extent(1, 2)),
            Some(2),
            4,
            1,
            true,
            "FEC storage extent overlaps hash tree data extent",
        ),
    ] {
        let temporary = TempDir::new().unwrap();
        let output_dir = temporary.path().join("output");
        let data = vec![0x5a; operation_blocks * 4096];
        let mut update = PartitionUpdate {
            partition_name: "vendor".into(),
            new_partition_info: Some(partition_info(&vec![0; partition_blocks * 4096])),
            operations: vec![InstallOperation {
                operation_type: 0,
                data_offset: Some(0),
                data_length: Some(data.len() as u64),
                dst_extents: vec![extent(0, operation_blocks as u64)],
                ..Default::default()
            }],
            fec_data_extent: data_extent,
            fec_extent: storage_extent,
            fec_roots: roots,
            ..Default::default()
        };
        if hash_tree {
            if partition_blocks == 4 {
                update.hash_tree_data_extent = Some(extent(0, 3));
                update.hash_tree_extent = Some(extent(3, 1));
            } else {
                update.hash_tree_data_extent = Some(extent(0, 1));
                update.hash_tree_extent = Some(extent(1, 1));
            }
            update.hash_tree_algorithm = Some("sha256".into());
        }
        let manifest = DeltaArchiveManifest {
            block_size: Some(4096),
            minor_version: Some(6),
            partitions: vec![update],
        };
        let payload = temporary.path().join("payload.bin");
        write_payload(&payload, manifest, &data);

        let actual = ExtractOptions::new().extract(&payload, &output_dir).unwrap_err().to_string();

        assert!(actual.contains(error), "unexpected error: {actual}");
        assert!(!output_dir.join("vendor.img").exists());
        assert!(fs::read_dir(&output_dir).unwrap().next().is_none());
    }
}

#[test]
fn verified_partitions_are_promoted_after_all_succeed() {
    let temporary = TempDir::new().unwrap();
    let output_dir = temporary.path().join("output");
    let boot = b"boot";
    let vendor = b"vend";
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(0),
        partitions: vec![
            PartitionUpdate {
                partition_name: "boot".into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(boot)),
                operations: vec![InstallOperation {
                    operation_type: 0,
                    data_offset: Some(0),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
                ..Default::default()
            },
            PartitionUpdate {
                partition_name: "vendor".into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(vendor)),
                operations: vec![InstallOperation {
                    operation_type: 0,
                    data_offset: Some(4),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
                ..Default::default()
            },
        ],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, b"bootvend");

    ExtractOptions::new().extract(&payload, &output_dir).unwrap();

    assert_eq!(fs::read(output_dir.join("boot.img")).unwrap(), boot);
    assert_eq!(fs::read(output_dir.join("vendor.img")).unwrap(), vendor);
}

#[test]
fn no_clobber_rejects_existing_destination_without_modifying_source() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    fs::create_dir(&output_dir).unwrap();
    let source = b"base";
    let existing = b"keep";
    fs::write(source_dir.join("system.img"), source).unwrap();
    fs::write(output_dir.join("system.img"), existing).unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(source)),
            new_partition_info: Some(partition_info(source)),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(0, 1)],
                dst_extents: vec![extent(0, 1)],
                ..Default::default()
            }],
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let error = ExtractOptions::new()
        .source_dir(&source_dir)
        .extract(&payload, &output_dir)
        .unwrap_err()
        .to_string();

    assert!(error.contains("already exists"));
    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), existing);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
    assert_eq!(fs::read_dir(&output_dir).unwrap().count(), 1);
}

#[test]
fn verification_failure_preserves_existing_destinations_with_overwrite() {
    let temporary = TempDir::new().unwrap();
    let output_dir = temporary.path().join("output");
    fs::create_dir(&output_dir).unwrap();
    fs::write(output_dir.join("boot.img"), b"oldb").unwrap();
    fs::write(output_dir.join("vendor.img"), b"oldv").unwrap();
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(0),
        partitions: vec![
            PartitionUpdate {
                partition_name: "boot".into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(b"boot")),
                operations: vec![InstallOperation {
                    operation_type: 0,
                    data_offset: Some(0),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
                ..Default::default()
            },
            PartitionUpdate {
                partition_name: "vendor".into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(b"bad!")),
                operations: vec![InstallOperation {
                    operation_type: 0,
                    data_offset: Some(4),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
                ..Default::default()
            },
        ],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, b"bootvend");

    let error = ExtractOptions::new()
        .overwrite(true)
        .extract(&payload, &output_dir)
        .unwrap_err()
        .to_string();

    assert!(error.contains("Output verification failed"));
    assert_eq!(fs::read(output_dir.join("boot.img")).unwrap(), b"oldb");
    assert_eq!(fs::read(output_dir.join("vendor.img")).unwrap(), b"oldv");
    assert_eq!(fs::read_dir(&output_dir).unwrap().count(), 2);
}

#[test]
fn partition_selection_does_not_require_unselected_delta_sources() {
    let temporary = TempDir::new().unwrap();
    let output_dir = temporary.path().join("output");
    let expected = b"boot";
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![
            PartitionUpdate {
                partition_name: "boot".into(),
                old_partition_info: None,
                new_partition_info: Some(partition_info(expected)),
                operations: vec![InstallOperation {
                    operation_type: 0,
                    data_offset: Some(0),
                    data_length: Some(4),
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
                ..Default::default()
            },
            PartitionUpdate {
                partition_name: "system".into(),
                old_partition_info: Some(partition_info(b"base")),
                new_partition_info: Some(partition_info(b"base")),
                operations: vec![InstallOperation {
                    operation_type: 4,
                    src_extents: vec![extent(0, 1)],
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
                ..Default::default()
            },
        ],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, expected);

    ExtractOptions::new().partitions(["boot"]).extract(&payload, &output_dir).unwrap();

    assert_eq!(fs::read(output_dir.join("boot.img")).unwrap(), expected);
    assert!(!output_dir.join("system.img").exists());
}

struct CancellingReporter {
    cancellation_token: CancellationToken,
    cancelled: AtomicBool,
}

impl ProgressReporter for CancellingReporter {
    fn report_progress(&self, progress: f64) {
        if progress > 0.0 && !self.cancelled.swap(true, Ordering::AcqRel) {
            self.cancellation_token.cancel();
        }
    }
}

#[test]
fn cancellation_cleans_staging_without_promoting_or_modifying_source() {
    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    fs::create_dir(&output_dir).unwrap();
    let source = (0..128).map(|byte| byte as u8).collect::<Vec<_>>();
    fs::write(source_dir.join("system.img"), &source).unwrap();
    let existing = b"existing destination";
    fs::write(output_dir.join("system.img"), existing).unwrap();
    let operations = (0..32)
        .map(|block| InstallOperation {
            operation_type: 4,
            src_extents: vec![extent(block, 1)],
            src_length: Some(4),
            dst_extents: vec![extent(block, 1)],
            dst_length: Some(4),
            ..Default::default()
        })
        .collect();
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(&source)),
            new_partition_info: Some(partition_info(&source)),
            operations,
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);
    let cancellation_token = CancellationToken::new();
    let reporter = CancellingReporter {
        cancellation_token: cancellation_token.clone(),
        cancelled: AtomicBool::new(false),
    };

    let error = ExtractOptions::new()
        .source_dir(&source_dir)
        .overwrite(true)
        .num_threads(4)
        .progress_reporter(&reporter)
        .cancellation_token(&cancellation_token)
        .extract(&payload, &output_dir)
        .unwrap_err();

    assert!(is_cancellation(error.as_ref()));
    assert_eq!(fs::read(output_dir.join("system.img")).unwrap(), existing);
    assert_eq!(fs::read(source_dir.join("system.img")).unwrap(), source);
    assert!(
        fs::read_dir(&output_dir).unwrap().all(|entry| !entry
            .unwrap()
            .file_name()
            .to_string_lossy()
            .starts_with(".otadump-"))
    );
}

#[test]
fn cli_extraction_error_exits_nonzero_and_reports_diagnostic() {
    use std::process::Command;

    let temporary = TempDir::new().unwrap();
    let payload = temporary.path().join("payload.bin");
    let output_dir = temporary.path().join("output");
    let manifest = DeltaArchiveManifest {
        block_size: Some(4),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "boot".into(),
            old_partition_info: Some(partition_info(b"base")),
            new_partition_info: Some(partition_info(b"base")),
            operations: vec![InstallOperation {
                operation_type: 4,
                src_extents: vec![extent(0, 1)],
                dst_extents: vec![extent(0, 1)],
                ..Default::default()
            }],
            ..Default::default()
        }],
    };
    write_payload(&payload, manifest, &[]);

    let output = Command::new(env!("CARGO_BIN_EXE_otadump"))
        .arg(&payload)
        .arg("--output-dir")
        .arg(&output_dir)
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert_eq!(output.status.code(), Some(1), "CLI did not exit with code 1; stderr: {stderr}");
    assert!(
        stderr.contains("require a source directory"),
        "missing extraction diagnostic: {stderr}"
    );
}

#[cfg(unix)]
#[test]
fn cli_sigint_exits_130_after_cleaning_staging() {
    use std::process::{Command, Stdio};
    use std::time::{Duration, Instant};

    let temporary = TempDir::new().unwrap();
    let source_dir = temporary.path().join("source");
    let output_dir = temporary.path().join("output");
    fs::create_dir(&source_dir).unwrap();
    let block_size = 256usize;
    let block_count = 65_536usize;
    let source = vec![0x5a; block_size * block_count];
    let source_path = source_dir.join("system.img");
    fs::write(&source_path, &source).unwrap();
    let operations = (0..block_count)
        .map(|block| InstallOperation {
            operation_type: 4,
            src_extents: vec![extent(block as u64, 1)],
            src_length: Some(block_size as u64),
            dst_extents: vec![extent(block as u64, 1)],
            dst_length: Some(block_size as u64),
            ..Default::default()
        })
        .collect();
    let manifest = DeltaArchiveManifest {
        block_size: Some(block_size as u32),
        minor_version: Some(2),
        partitions: vec![PartitionUpdate {
            partition_name: "system".into(),
            old_partition_info: Some(partition_info(&source)),
            new_partition_info: Some(partition_info(&source)),
            operations,
            ..Default::default()
        }],
    };
    let payload = temporary.path().join("payload.bin");
    write_payload(&payload, manifest, &[]);

    let mut child = Command::new(env!("CARGO_BIN_EXE_otadump"))
        .arg(&payload)
        .arg("--output-dir")
        .arg(&output_dir)
        .arg("--source-dir")
        .arg(&source_dir)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .unwrap();
    let deadline = Instant::now() + Duration::from_secs(10);
    loop {
        let staging_exists = output_dir.exists()
            && fs::read_dir(&output_dir)
                .unwrap()
                .any(|entry| entry.unwrap().file_name().to_string_lossy().starts_with(".otadump-"));
        if staging_exists {
            break;
        }
        assert!(child.try_wait().unwrap().is_none(), "CLI finished before SIGINT");
        assert!(Instant::now() < deadline, "staging directory was not created");
        std::thread::yield_now();
    }
    let signal_status =
        Command::new("kill").arg("-INT").arg(child.id().to_string()).status().unwrap();
    assert!(signal_status.success());
    let exit_deadline = Instant::now() + Duration::from_secs(10);
    let status = loop {
        if let Some(status) = child.try_wait().unwrap() {
            break status;
        }
        if Instant::now() >= exit_deadline {
            child.kill().unwrap();
            child.wait().unwrap();
            panic!("CLI did not finish cleanup after SIGINT");
        }
        std::thread::sleep(Duration::from_millis(1));
    };

    assert_eq!(status.code(), Some(130));
    assert!(!output_dir.join("system.img").exists());
    assert_eq!(sha256(&fs::read(source_path).unwrap()), sha256(&source));
    assert!(fs::read_dir(&output_dir).unwrap().next().is_none());
}

#[cfg(unix)]
#[test]
fn source_and_destination_aliases_are_rejected_without_modifying_the_source() {
    use std::os::unix::fs::symlink;

    for link in ["hard", "symbolic"] {
        let temporary = TempDir::new().unwrap();
        let source_dir = temporary.path().join("source");
        let output_dir = temporary.path().join("output");
        fs::create_dir(&source_dir).unwrap();
        fs::create_dir(&output_dir).unwrap();
        let source_path = source_dir.join("system.img");
        let source = b"base";
        fs::write(&source_path, source).unwrap();
        let destination_path = output_dir.join("system.img");
        if link == "hard" {
            fs::hard_link(&source_path, &destination_path).unwrap();
        } else {
            symlink(&source_path, &destination_path).unwrap();
        }

        let manifest = DeltaArchiveManifest {
            block_size: Some(4),
            minor_version: Some(2),
            partitions: vec![PartitionUpdate {
                partition_name: "system".into(),
                old_partition_info: Some(partition_info(source)),
                new_partition_info: Some(partition_info(source)),
                operations: vec![InstallOperation {
                    operation_type: 4,
                    src_extents: vec![extent(0, 1)],
                    dst_extents: vec![extent(0, 1)],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        };
        let payload = temporary.path().join("payload.bin");
        write_payload(&payload, manifest, &[]);

        let error = ExtractOptions::new()
            .source_dir(&source_dir)
            .overwrite(true)
            .extract(&payload, &output_dir)
            .unwrap_err()
            .to_string();

        assert!(error.contains("refer to the same file"));
        assert_eq!(fs::read(&source_path).unwrap(), source);
    }
}
